'use client'

import { useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, CheckCheck, ChevronRight, CircleAlert, Download, FileCheck2, FileText, Fingerprint, LockKeyhole, Mail, ScanLine, ShieldCheck } from 'lucide-react'
import { canApprove, documentHTML, FIELD_LABELS, formatDate, pendingIssues, scenarioFor } from '@/lib/showcase'
import type { DocumentCase, Issue, ReviewTab } from '@/lib/showcase'
import { EntityMark, Status } from './Overview'

export function AuditTrail({ item }: { item: DocumentCase }) {
  return <ol className="audit-list">{item.audit.map((entry, i) => <li key={entry.id}><div className={`audit-marker ${entry.kind}`} aria-hidden="true">{entry.kind === 'approved' ? <CheckCheck size={15} /> : entry.kind === 'review' ? <Fingerprint size={15} /> : <span>{String(i + 1).padStart(2, '0')}</span>}</div><div className="audit-content"><span className="audit-actor">{entry.actor}</span><h3>{entry.action}</h3><p>{entry.detail}</p></div><time dateTime={entry.at}>{formatDate(entry.at)}</time></li>)}</ol>
}

function Exception({ issue, onResolve, item }: { issue: Issue; onResolve: (issue: string, value: string, reason: string) => void; item: DocumentCase }) {
  const [choice, setChoice] = useState(issue.resolution?.value || '')
  const [value, setValue] = useState(issue.resolution?.value || '')
  const [reason, setReason] = useState(issue.resolution?.reason || '')
  return <div className="exception-card"><div className="exception-header"><CircleAlert size={19} /><div><span className="eyebrow">{issue.kind === 'conflict' ? 'CONFLICTING EVIDENCE' : 'MISSING REQUIRED INFORMATION'}</span><h3>{FIELD_LABELS[issue.field]} needs your judgment.</h3></div><span className="held-label"><LockKeyhole size={12} /> {issue.resolution ? 'Decision recorded' : 'Approval held'}</span></div><p>{issue.description}</p>
    {issue.kind === 'conflict' ? <div className="evidence-choices">{issue.options.map(option => <button key={option.sourceId} className={`evidence-choice ${choice === option.value ? 'selected' : ''}`} onClick={() => setChoice(option.value)} aria-pressed={choice === option.value}><span className="choice-top"><FileText size={14} />{option.label}<span className="choice-radio">{choice === option.value && <span />}</span></span><b>{option.value}</b><small>{item.sources.find(s => s.id === option.sourceId)?.name}<br />{formatDate(item.sources.find(s => s.id === option.sourceId)?.recordedAt || item.createdAt)}</small></button>)}</div> : <div className="missing-input"><label htmlFor={`missing-${issue.id}`}>Reviewer-provided {FIELD_LABELS[issue.field].toLowerCase()}</label><input id={`missing-${issue.id}`} value={value} maxLength={500} onChange={e => setValue(e.target.value)} placeholder={`Enter the ${FIELD_LABELS[issue.field].toLowerCase()}`} /><small>Your entry will be recorded as reviewer-provided information.</small></div>}
    <label className="decision-reason">Decision reason<textarea aria-label="Decision reason" value={reason} maxLength={500} onChange={e => setReason(e.target.value)} placeholder="What evidence supports this decision?" /></label>
    <div className="exception-footer"><span><Fingerprint size={13} /> Your decision updates both documents.</span><button className="button primary small" disabled={reason.trim().length < 3 || (issue.kind === 'conflict' ? !choice : !value.trim())} onClick={() => onResolve(issue.id, issue.kind === 'conflict' ? choice : value, reason)}><Check size={14} /> {issue.resolution ? 'Save revised decision' : 'Record decision'}</button></div>
  </div>
}

export function DocumentPreview({ item, index = 0 }: { item: DocumentCase; index?: number }) {
  // Both preview and download use this escaped, state-derived document renderer.
  return <div dangerouslySetInnerHTML={{ __html: documentHTML(item, index) }} />
}

export function CaseReview({ item, onBack, onResolve, onApprove, onDownload, readOnly = false }: { item: DocumentCase; onBack: () => void; onResolve: (issue: string, value: string, reason: string) => void; onApprove: () => void; onDownload: () => void; readOnly?: boolean }) {
  const [tab, setTab] = useState<ReviewTab>('facts')
  const [sourceId, setSourceId] = useState('intake')
  const [highlight, setHighlight] = useState('')
  const [documentIndex, setDocumentIndex] = useState(0)
  const [returnFact, setReturnFact] = useState('')
  useEffect(() => { if (tab === 'sources' && highlight) requestAnimationFrame(() => { const excerpt = document.querySelector<HTMLElement>('.source-section.highlighted'); excerpt?.scrollIntoView({ block: 'center' }); excerpt?.focus({ preventScroll: true }) }) }, [tab, highlight, sourceId])
  const s = scenarioFor(item.scenario)
  const issues = pendingIssues(item)
  const source = item.sources.find(source => source.id === sourceId) || item.sources[0]
  function inspect(id: string, quote = '', key = '') { setReturnFact(key); setSourceId(id === 'reviewer' ? 'intake' : id); setHighlight(quote); setTab('sources') }
  return <div className="case-review view-enter"><button className="back-button" onClick={onBack}><ArrowLeft size={14} /> Back to document queue</button><header className="case-heading"><EntityMark item={item} /><div className="case-heading-title"><div className="eyebrow">{item.id} <ChevronRight size={10} /> {s.title}</div><h1>{item.name}</h1><Status status={item.status} /><p className="case-operational-meta">{item.assignee} · Received {formatDate(item.createdAt)}<br />Due {formatDate(item.dueAt)} · Latest activity {formatDate(item.updatedAt)}</p></div><div className="case-heading-actions">{item.status === 'approved' ? <button className="button primary" onClick={onDownload}><Download size={16} /> Download packet</button> : <button className="button primary" disabled={readOnly || !canApprove(item)} onClick={onApprove}><Fingerprint size={16} /> Review & approve</button>}</div></header>
      <div className="case-progress" aria-label="Document workflow progress">{[{ name: 'Sources collected', detail: `${item.sources.length} extracts`, icon: LayersIcon }, { name: 'Facts interpreted', detail: 'Source-linked fields', icon: ScanLine }, { name: 'Cross-checked', detail: issues.length ? `${issues.length} exception` : 'Sources compared', icon: ShieldCheck }, { name: 'Draft prepared', detail: '2 documents', icon: FileCheck2 }, { name: 'Human approval', detail: item.status === 'approved' ? 'Confirmed' : 'Your decision', icon: Fingerprint }].map(({ name, detail, icon: Icon }, i) => <div className={`case-step ${i === 2 && issues.length ? 'attention' : i === 4 && item.status !== 'approved' ? 'waiting' : 'complete'}`} key={name}><span className="step-icon"><Icon size={17} /></span><div><b>{name}</b><small>{detail}</small></div>{i < 4 && <ArrowRight className="step-arrow" size={13} />}</div>)}</div>
      <details className="mobile-progress"><summary>{item.status === 'blocked' ? 'Approval held · review required' : item.status === 'approved' ? 'Packet approved · download available' : 'Draft ready · human review next'}</summary><ol><li>Source extracts collected</li><li>Facts linked to sources</li><li>{issues.length ? 'Required exceptions need a decision' : 'Required checks complete'}</li><li>Draft documents prepared</li><li>{item.status === 'approved' ? 'Human approval recorded' : 'Human approval pending'}</li></ol></details>
      <div className="case-tabs" role="tablist" aria-label="Case information">{[{ id: 'facts', label: 'Business facts', icon: ScanLine, count: item.facts.length }, { id: 'sources', label: 'Source files', icon: FileText, count: 3 }, { id: 'documents', label: 'Documents', icon: FileCheck2, count: 2 }, { id: 'audit', label: 'Audit trail', icon: ShieldCheck, count: item.audit.length }].map(({ id, label, icon: Icon, count }, i) => <button key={id} role="tab" aria-selected={tab === id} aria-controls={`case-panel-${id}`} id={`case-tab-${id}`} tabIndex={tab === id ? 0 : -1} onClick={() => setTab(id as ReviewTab)} onKeyDown={e => { if (['ArrowRight', 'ArrowLeft', 'Home', 'End'].includes(e.key)) { e.preventDefault(); const next = e.key === 'Home' ? 0 : e.key === 'End' ? 3 : (i + (e.key === 'ArrowRight' ? 1 : 3)) % 4; const ids: ReviewTab[] = ['facts', 'sources', 'documents', 'audit']; setTab(ids[next]); document.getElementById(`case-tab-${ids[next]}`)?.focus() } }}><Icon size={15} />{label}<span>{count}</span></button>)}</div>
      <section id={`case-panel-${tab}`} role="tabpanel" aria-labelledby={`case-tab-${tab}`} className="case-tab-panel">
      {tab === 'facts' && <><div className="review-layout"><div className="facts-main">{issues.map(issue => <fieldset disabled={readOnly} className="exception-fieldset" key={issue.id}><Exception item={item} issue={issue} onResolve={onResolve} /></fieldset>)}{item.status !== 'approved' && item.issues.filter(issue => issue.resolution).map(issue => <details className="revised-decision" key={issue.id}><summary>Revise {FIELD_LABELS[issue.field].toLowerCase()} decision</summary><fieldset disabled={readOnly} className="exception-fieldset"><Exception key={`${issue.id}-${issue.resolution?.value}`} item={item} issue={issue} onResolve={onResolve} /></fieldset></details>)}{!issues.length && <div className="clear-banner"><CheckCheck size={19} /><div><b>{item.status === 'approved' ? 'Your approved packet is ready.' : 'The required checks are complete.'}</b><span>{item.status === 'approved' ? 'Both documents reflect the confirmed values below.' : 'Inspect the prepared documents, then give the final approval.'}</span></div><button onClick={() => setTab('documents')}>View documents <ArrowRight size={14} /></button></div>}
        <div className="facts-card"><header className="panel-heading"><div><span className="eyebrow">CASE FACTS &amp; EVIDENCE</span><h2>Business facts</h2></div><span className="subtle-pill">{item.facts.length} mapped fields</span></header><div className="facts-table"><div className="facts-table-head"><span>FIELD / VALUE</span><span>SOURCE EVIDENCE</span><span>STATUS</span></div>{item.facts.map(f => { const unresolved = issues.some(i => i.field === f.key) || (!f.value.trim() && item.required.includes(f.key)); const resolved = item.issues.some(i => i.field === f.key && i.resolution); return <div className={`fact-row ${unresolved ? 'flagged' : ''}`} key={f.key} id={`fact-${f.key}`} tabIndex={-1}><div><span className="fact-label">{FIELD_LABELS[f.key]}</span><b>{f.value.trim() || 'Not supplied'}</b></div><div>{f.sourceId === 'reviewer' ? <span className="reviewer-source"><Fingerprint size={12} /> Reviewer provided</span> : <button className="source-link" onClick={() => inspect(f.sourceId, f.quote, f.key)}><FileText size={12} />{f.sourceId === 'email' ? 'Confirmation email' : f.sourceId === 'record' ? 'Business record' : 'Intake form'}<ArrowUpRight size={12} /></button>}</div><span className={`fact-state ${unresolved ? 'attention' : ''}`}>{unresolved ? <CircleAlert size={12} /> : resolved ? <Fingerprint size={12} /> : f.value.trim() ? <FileText size={12} /> : null}{unresolved ? 'Review' : resolved ? 'Reviewer selected' : f.value.trim() ? 'Recorded' : 'Optional'}</span></div> })}</div>{item.context.length > 0 && <dl className="workflow-context">{item.context.map(f => <div key={f.label}><dt>{f.label}</dt><dd>{f.value}<small>Submitted intake form</small></dd></div>)}</dl>}<div className="facts-card-footer"><ShieldCheck size={14} /> Source evidence stays with the value, all the way to the document.</div></div></div>
        <aside className="review-aside"><div className="mini-packet"><span className="eyebrow">PREPARED FROM THESE FACTS</span><div className="mini-document-art"><FileCheck2 size={30} strokeWidth={1.15} /><div /><div /><div /></div><h3>{s.output}</h3><p>+ verification record</p><button className="button secondary small" onClick={() => setTab('documents')}>Inspect both documents <ArrowUpRight size={13} /></button></div><div className="boundary-note"><Fingerprint size={20} /><b>You make the final call.</b><p>{issues.length ? 'DAAM pauses at uncertain information. Resolve the difference before approving this packet.' : 'DAAM prepares the packet. A human reviewer approves the facts and documents.'}</p><span>No automatic sending or signing.</span></div></aside></div></>}
      {tab === 'sources' && <div className="source-layout"><aside className="source-picker"><span className="eyebrow">SOURCE EXTRACTS</span><h2>Three files. One case.</h2><p>Inspect the provided extract behind each mapped fact.</p>{item.sources.map(doc => <button className={`source-file ${doc.id === source.id ? 'active' : ''}`} key={doc.id} onClick={() => { setSourceId(doc.id); setHighlight('') }}><span className="source-file-icon">{doc.kind === 'EMAIL' ? <Mail size={18} /> : <FileText size={18} />}</span><span><b>{doc.name}</b><small>{doc.origin}</small></span><span className="file-type">{doc.kind}</span></button>)}<div className="source-disclosure"><ShieldCheck size={16} /><p>Compare the source extract with its mapped facts. Differences stay on hold until a reviewer resolves them.</p></div></aside><div className="source-viewer"><div className="source-toolbar"><span><FileText size={15} />{source.name}</span><span>Source extract</span></div>{returnFact && <button className="button secondary small source-return" onClick={() => { setTab('facts'); requestAnimationFrame(() => { const fact = document.getElementById(`fact-${returnFact}`); fact?.scrollIntoView({ block: 'center' }); fact?.focus() }) }}>Return to selected fact <ArrowLeft size={14} /></button>}<article className="source-sheet"><div className="source-sheet-heading"><span className="eyebrow">{source.kind === 'EMAIL' ? 'EMAIL / PROVIDED EXTRACT' : source.kind === 'RECORD' ? 'BUSINESS RECORD / SNAPSHOT' : 'INTAKE / SUBMITTED INFORMATION'}</span><h2>{source.kind === 'EMAIL' ? 'Onboarding confirmation' : source.kind === 'RECORD' ? 'Existing business record' : `${s.title} form`}</h2><p>{item.name} · {item.facts.find(f => f.key === 'reference')?.value}</p></div>{source.sections.map((section, index) => <div className={`source-section ${highlight && section.body.includes(highlight) ? 'highlighted' : ''}`} key={index} tabIndex={-1}><span>{section.label}</span><p>{section.body}</p>{highlight && section.body.includes(highlight) && <small><ScanLine size={12} /> Source of selected fact</small>}</div>)}<footer>Provided source extract · original file is not rendered here</footer></article></div></div>}
      {tab === 'documents' && <div className="documents-layout"><aside className="document-picker"><span className="eyebrow">ONE RECORD. TWO OUTPUTS.</span><h2>Your prepared packet.</h2><p>Values carry into each document through reusable field mappings.</p>{[s.output, 'Verification record'].map((name, index) => <button className={`document-choice ${documentIndex === index ? 'active' : ''}`} key={name} onClick={() => setDocumentIndex(index)}><FileText size={19} /><span><b>{name}</b><small>{item.status === 'approved' ? 'Approved for download' : 'Draft · human review required'}</small></span><span>0{index + 1}</span></button>)}<div className="document-gate"><Fingerprint size={21} /><h3>{item.status === 'approved' ? 'Reviewed. Recorded. Ready.' : issues.length ? `Confirm the ${FIELD_LABELS[issues[0]?.field || 'address'].toLowerCase()}.` : 'Give the final approval.'}</h3><p>{item.status === 'approved' ? 'Download a printable HTML packet. Your browser can save it as PDF.' : issues.length ? 'Resolve the source exception before this packet can be approved.' : 'Confirm you have reviewed the facts and both documents.'}</p>{item.status === 'approved' ? <button className="button primary" onClick={onDownload}><Download size={15} /> Download packet</button> : <button className="button primary" disabled={readOnly || !canApprove(item)} onClick={onApprove}><Fingerprint size={15} /> Review & approve</button>}</div><p className="document-disclosure">The packet includes source references and the recorded review decisions.</p></aside><div className="document-canvas"><div className="document-canvas-toolbar"><span><FileCheck2 size={15} />{documentIndex === 0 ? s.output : 'Verification record'}</span><span>{item.status === 'approved' ? <><Check size={12} /> Approved</> : 'Draft preview'}</span></div><DocumentPreview item={item} index={documentIndex} /></div></div>}
      {tab === 'audit' && <div className="audit-panel"><header className="panel-heading"><div><span className="eyebrow">EVERY STEP ACCOUNTED FOR</span><h2>Case activity</h2><p>From source intake to your final decision.</p></div><span className="subtle-pill">{item.audit.length} recorded steps</span></header><AuditTrail item={item} /><div className="audit-footer"><ShieldCheck size={16} />Reviewer decisions and source references are recorded with each case.</div></div>}
      </section>
  </div>
}
function LayersIcon({ size = 18 }: { size?: number }) { return <FileText size={size} /> }
